[theme]
primaryColor = "#1f77b4"
backgroundColor = "#181616"
secondaryBackgroundColor = "#8b8d91"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
